version: 0.0.1.{build}

shallow_clone: true

cache:
  - "%APPDATA%\\stack"
  - .stack-work

build_script:
  - choco install haskell-stack
  - cd .. && stack --no-terminal --resolver nightly-2018-03-01 setup > NUL && stack --no-terminal install hpack && cd spellbook
  - stack --no-terminal --with-hpack=C:\\Users\\appveyor\\AppData\\Roaming\\local\\bin\\hpack.exe build --haddock --test

test: off
