version: 0.0.1.{build}

shallow_clone: true

cache:
  - "%APPDATA%\\stack"
  - .stack-work

build_script:
  - choco install haskell-stack
  - stack --no-terminal setup > NUL
  - stack --no-terminal --resolver nightly-2018-03-01 install hpack
  - stack --no-terminal --with-hpack=hpack.exe build --haddock --test

test: off
